language: node_js

node_js:
  - "6"

before_install:
  - npm install

script:
  - npm run test
  - npm run lint

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

env:
  global:
    - secure: "SO1kYziAZq8Mncf2w4enF5rqPRBLtnc75RnqmBjirgthJe5INdLI13dHyQ038Sa4148IuNqHzBhoKSwAhO1kEfA853W9IEB/U4GyprnAhRrZp9Mkpw6D0S3r3SmtuVxEtgARLZKQe6iVD46T2s+xci/p9af91OAVkjVL669hXgZji8WUG6786sKwjx0HOC1JlifAzM7b9STmib9ep9lkVMcHkAhIA4pIkxN5ic+URThWm9C/3v0k2eh4tIdCFxRvcqKAeneCTFo0BUH+8WK8ORVKIpvXReO1KU6UhFqqaguEg1z2i+tN551xTe/o7GZbS8UYPbzeZXpJ9ISg3/v1Tk00NphAa4+JwEv3wctO0JE6P1KtAHPvq7ZCEhE7ZySWEK+SdoIT0rifjXyNUceTAjjokZqU63ionXIfZwWCgJiooaCqNnfaEPHVMLyxeTcLNMzLu6SDy+vHI0KBhPHo66jzFCAlBtH0Kmbsn/oZSN3ha95f8lF87CbJsPicExzH5esljmOEUQ+UqYl7WVCrbKmR8JtX/pEdkzDedv0CFFzQ1gHG7i0XuviPWaEKaegP4kFO/RppgRReuCrWcET8YbXE4ov2mpmX3GANvYWxACmpIKHNBakEodriUzsJSaqrQPJE3oWYGnwPXelGlC/9cYCVGZmn5yFNrb+KQMK2CUQ="
