language: node_js

node_js:
  - '6'

before_install:
  - npm install

script:
  - npm run test
  - npm run lint

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

env:
  global:
  - secure: SO1kYziAZq8Mncf2w4enF5rqPRBLtnc75RnqmBjirgthJe5INdLI13dHyQ038Sa4148IuNqHzBhoKSwAhO1kEfA853W9IEB/U4GyprnAhRrZp9Mkpw6D0S3r3SmtuVxEtgARLZKQe6iVD46T2s+xci/p9af91OAVkjVL669hXgZji8WUG6786sKwjx0HOC1JlifAzM7b9STmib9ep9lkVMcHkAhIA4pIkxN5ic+URThWm9C/3v0k2eh4tIdCFxRvcqKAeneCTFo0BUH+8WK8ORVKIpvXReO1KU6UhFqqaguEg1z2i+tN551xTe/o7GZbS8UYPbzeZXpJ9ISg3/v1Tk00NphAa4+JwEv3wctO0JE6P1KtAHPvq7ZCEhE7ZySWEK+SdoIT0rifjXyNUceTAjjokZqU63ionXIfZwWCgJiooaCqNnfaEPHVMLyxeTcLNMzLu6SDy+vHI0KBhPHo66jzFCAlBtH0Kmbsn/oZSN3ha95f8lF87CbJsPicExzH5esljmOEUQ+UqYl7WVCrbKmR8JtX/pEdkzDedv0CFFzQ1gHG7i0XuviPWaEKaegP4kFO/RppgRReuCrWcET8YbXE4ov2mpmX3GANvYWxACmpIKHNBakEodriUzsJSaqrQPJE3oWYGnwPXelGlC/9cYCVGZmn5yFNrb+KQMK2CUQ=

deploy:
  provider: npm
  email:
    secure: "EqqOehMbUFdR0vJQ+diOu4nWz3kfPtIT1tZPDDckDzdXNaLwh5fsta7M3y9DPqOxpnpUlILD//oiJkvBsd3hKWOncDdoA/lV2Hs5JszkRYsDCTzgZX0pFWH9wI/HMy0Y1PQ9SSBY4OB1R58pvxjDWxGjHaetG1CKty5yLE4dNzBA0Ul8u/upxbr8box+yaB5K3h1MpZloLFIbICdFmjByR0kPh+StNf1XFRuk/nPlXbRF4A4MKLD1yfogiM8YlJyxx6oF0JCs/4yvA0GorXWU1wpOiNrE4bjixjgHQi5eMUwqd6qkTSg8Fpb00tV4O8RrVbDu6fCQfrtF0SmHAQXO5yY/MeMp3e8jPxyy3OaZ7dURnceuqQaQ9kPxRXoJIqLMdZcgJpWqWZPmJbJmOBjchgDqZWyuhjLzUU6cKduou/uJ8i3JneVDUcFzNgSKvv77say7TsVN0QBXISyYBaHq66G8xE0ndYF4bjqfWe43UyGZaXumDY67712hmp4OevX2uohniWjzBJD+urktPkpvV24Pq3JpQKbekz3LBPDFEk3WeUQbu2KUKC9cvcMvCfP3NY7PNN4glfkllQyX+d2vhQDf6ixm4lcnimuIni7kcGTUMydkpT6r5w0yAS1NL50lTfGQY+7n+1m9ohyclqucuKRlzetBZ4p5gaHk0nJbxc="
  api_key:
    secure: H7kKppxgC8S3qXDIUtGz94J2lpbXeMdL9B3wXEop6PGoEw7IF8WSrgaQffrO91TEygyoryPlQScneVm+X8FR95ytyHqt8Ikw7uomjfIHhUgE52yi4RluRcPliH+eLyDALEs4LI8+XV68fGRVTLfUqFPXiJ7E9k5AI7BOkBhsqKRFMhbqLRR6G8XcTkfed0NGrqkkyfO63Cds4UkdIKHC7N/bTqbjPIH+XT/k487RPP45MByr9Bm9/zZT19UOch13a/axUZ6BP0aLZkPEX0KnDsKrhd4WsTm30Z5MOYorgLyhCb3uS+avHIHDiB6nsrqY1eggfCEipb9t4BMcIdNQNzMn0sEcC7cvW8As5vbiAO/szbsFRrjwVvg3phO7UD/ZSONfusP1ytefKRxmN0iIF1v17bNn9+q58GX7KMHeNjfySb3uzeeAfMwDfs4JNExFQuKGhkQMjlQFlwM/GZ7faTVaOlkKKtXZvwMc1NhXl15N4StQfEG4uNr/oa3xTQbJCrt2ACOY5Qil+tUYX49MYOCQmt8puvhj64K+J/2O3hkNyq+Uww6GHXNNbGf8+QJEu8sd4LKd17pb0LDjiQTweuUAJbSD6funN4pgQa9Xm34d5Wn41omJRqFrpKNRhBivMin11DecmjVvnfNHUjTPF38RbMQ4HZ86p/wHHD0MuBw=
  on:
    tags: true
    repo: notonthehighstreet/node-lambda-events
