language: node_js

node_js:
  - "6"

before_install:
  - npm install

script:
  - npm run test
  - npm run lint

after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info

env:
  global:
    - secure: 
