FROM node:6.6

ENV PATH=/node_modules/.bin:$PATH NODE_PATH=$NODE_PATH:/node_modules

WORKDIR /

ADD package.json /package.json

RUN NODE_ENV=production npm install --silent 1>/dev/null

ADD . /app

WORKDIR /app
